<?xml version="1.0"?>
<package format="3">
  <name>grobot_mapping</name>
  <version>0.1.0</version>
  <description>SLAM and map generation launch files for GRobot.</description>
  <maintainer email="654369841@qq.com">Grampus.K</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>cartographer_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
